Merged r52342 from trunk: Fixed error introduced by previous commit r52328: AttributeError: 'NoneType' object has no attribute 'getTypeInfo'. Refs #8198
svn path=/plone.app.layout/branches/2.1/; revision=52343