Prevent KeyError getting ISiteSchema when not all records exist yet.
We need to run an upgrade step to define the new `webstats_head_js` field, but it would be nice if the UI looks reasonable before this.
Various viewlets give:

KeyError: 'Interface `plone.base.interfaces.controlpanel.ISiteSchema` defines a field `webstats_head_js`, for which there is no record.'